services:
  - type: web
    name: sahel-oxygene-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: '5'
      - key: SUPER_ADMIN_EMAILS
        value: admin1@sahelox.bf,admin2@sahelox.bf,derboadama31@gmail.com
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DB_SSL
        value: "true"
      - key: JWT_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        value: "https://saheloxygene.com,http://localhost:5173"
      - key: PUBLIC_APP_URL
        value: "https://saheloxygene.com"
      - key: ADMIN_WHATSAPP_PRINCIPAL
        value: "22607144118"
